name: Metrics

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      #  Achievements
      - name:  Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: 85d5e70c0b12cc7f904df11fd3880f55
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_fortune: yes

      #  Sponsors
      - name:  Sponsors
        uses: lowlighter/metrics@latest
        with:
          filename: sponsors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          output_action: gist
          committer_gist: 85d5e70c0b12cc7f904df11fd3880f55
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsorships: yes
          plugin_sponsorships_sections: amount

      #  General Metrics
      - name:  General
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          theme: dark
          base: header
          base_indepth: yes
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          output_action: gist
          committer_gist: 85d5e70c0b12cc7f904df11fd3880f55

          plugin_isocalendar: yes

          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, sh, gnuplot, vue, scala, c, python, ejs
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 2

          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_self: yes
          plugin_notable_repositories: render.phisher
          plugin_discussions: yes

      #  Recent Activity
      - name:  Recent Activity
        uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          theme: dark
          base: ""
          output_action: gist
          committer_gist: 85d5e70c0b12cc7f904df11fd3880f55
          plugin_activity: yes
          plugin_activity_limit: 5 # Number of events to display
          plugin_activity_days: 14 # Number of days to consider
          plugin_activity_types: issue, pr, release, push

      #  Featured Repository
      - name:  Featured Repository
        uses: lowlighter/metrics@latest
        with:
          filename: featured.svg
          token: ${{ secrets.METRICS_TOKEN }}
          theme: dark
          base: ""
          output_action: gist
          committer_gist: 85d5e70c0b12cc7f904df11fd3880f55
          plugin_lines: yes
          plugin_followup: yes
          plugin_codeowners: yes
          plugin_repositories: yes
          plugin_repositories_featured: render.phisher, rendercam
